name: Vault active-active HA conformance testing

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add all of the tests you want to run under test.
        test:
          - TestGetTestCluster
          - TestServiceTokens
          - TestBatchTokens
          - TestPolicies
          - TestPKIMount
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.8'
      # A fresh mysql instance is already running :]
      # Tests run much slower with the race detector.
      - run: |
          go test -timeout 5m github.com/hashicorp/vault/active -race -run "^(${TEST})$"
        env:
          GOFLAGS: "-mod=vendor"
          # Race detector requires CGO_ENABLED=1 :[
          CGO_ENABLED: "1"
          TEST: ${{ matrix.test }}
          NUM_SERVERS: "3"
